{
 "title": "Docker daemon metrics",
 "description": "Docker daemon (engine) metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "engine_daemon_engine_info" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(engine_daemon_engine_info{instance=~'$instance'}) by (os, os_type, version)"
    }
   ]
  },
  {
   "title": "Engine cpus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running container",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=~'$instance', state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(engine_daemon_container_actions_seconds_count{instance=~'$instance'}[10m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Engine memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes{instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stopped container",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=~'$instance',state=\"stopped\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paused container",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=~'$instance', state=\"paused\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daemon network actions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(engine_daemon_network_actions_seconds_count{instance=~'$instance'}[10m])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Builds triggered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "rate(builder_builds_triggered_total{instance=~'$instance'}[30m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}