
filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /logs/flog_data/*
      tags: [ "flog" ]

    - type: log
      enabled: true
      paths:
        - /logs/log-generator_data/*
      tags: [ "log-generator" ]
      

processors:
  - drop_fields:
      fields: ["ecs", "input", "host", "agent", "log.offset"]
      ignore_missing: true

output.kafka:
  enabled: true
  hosts: ["kafka1:9091"]
  topic: filebeat-elk  #-%{[fields.topic]}
  worker: 2
  keep_alive: 60
  required_acks: 1

# output.elasticsearch:
#   hosts: [ "elasticsearch:9200" ] 
#   username: "admin"             
#   password: "admin"             
#   indices:
#     - index: "filebeat-elk-%{+yyyy.MM.dd}"
#       when.contains:
#         tags: "demo"